language: ruby
services:
  - mongodb
rvm:
  - 2.0.0
  - 2.1
  - 2.2
env:
  - USE_OFFICIAL_GEM_SOURCE=true
before_install: gem install bundler -v 1.10.5
notifications:
  recipients:
    - neverlandxy.naix@gmail.com
